//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDataServiceConsumer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFDataServiceConsumer.ServiceReference1.UniqueId MessageIDField;
        
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCFDataServiceConsumer.ServiceReference1.UniqueId MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniqueId", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UniqueId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFDataServiceConsumer.ServiceReference1.UniqueId MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCFDataServiceConsumer.ServiceReference1.UniqueId MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since element name GetDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        WCFDataServiceConsumer.ServiceReference1.GetDataResponse GetData(WCFDataServiceConsumer.ServiceReference1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetDataResponse> GetDataAsync(WCFDataServiceConsumer.ServiceReference1.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name composite from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponse GetDataUsingDataContract(WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest request);
        
        // CODEGEN: Generating message contract since element name person from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerson", ReplyAction="http://tempuri.org/IService1/GetPersonResponse")]
        WCFDataServiceConsumer.ServiceReference1.GetPersonResponse GetPerson(WCFDataServiceConsumer.ServiceReference1.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerson", ReplyAction="http://tempuri.org/IService1/GetPersonResponse")]
        System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetPersonResponse> GetPersonAsync(WCFDataServiceConsumer.ServiceReference1.GetPersonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(WCFDataServiceConsumer.ServiceReference1.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int value;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(WCFDataServiceConsumer.ServiceReference1.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataUsingDataContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataUsingDataContract", Namespace="http://tempuri.org/", Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequestBody Body;
        
        public GetDataUsingDataContractRequest() {
        }
        
        public GetDataUsingDataContractRequest(WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataUsingDataContractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.CompositeType composite;
        
        public GetDataUsingDataContractRequestBody() {
        }
        
        public GetDataUsingDataContractRequestBody(WCFDataServiceConsumer.ServiceReference1.CompositeType composite) {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataUsingDataContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataUsingDataContractResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponseBody Body;
        
        public GetDataUsingDataContractResponse() {
        }
        
        public GetDataUsingDataContractResponse(WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataUsingDataContractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponseBody() {
        }
        
        public GetDataUsingDataContractResponseBody(WCFDataServiceConsumer.ServiceReference1.CompositeType GetDataUsingDataContractResult) {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerson", Namespace="http://tempuri.org/", Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.GetPersonRequestBody Body;
        
        public GetPersonRequest() {
        }
        
        public GetPersonRequest(WCFDataServiceConsumer.ServiceReference1.GetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.Person person;
        
        public GetPersonRequestBody() {
        }
        
        public GetPersonRequestBody(WCFDataServiceConsumer.ServiceReference1.Person person) {
            this.person = person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.GetPersonResponseBody Body;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(WCFDataServiceConsumer.ServiceReference1.GetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCFDataServiceConsumer.ServiceReference1.Person GetPersonResult;
        
        public GetPersonResponseBody() {
        }
        
        public GetPersonResponseBody(WCFDataServiceConsumer.ServiceReference1.Person GetPersonResult) {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCFDataServiceConsumer.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCFDataServiceConsumer.ServiceReference1.IService1>, WCFDataServiceConsumer.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFDataServiceConsumer.ServiceReference1.GetDataResponse WCFDataServiceConsumer.ServiceReference1.IService1.GetData(WCFDataServiceConsumer.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string GetData(int value) {
            WCFDataServiceConsumer.ServiceReference1.GetDataRequest inValue = new WCFDataServiceConsumer.ServiceReference1.GetDataRequest();
            inValue.Body = new WCFDataServiceConsumer.ServiceReference1.GetDataRequestBody();
            inValue.Body.value = value;
            WCFDataServiceConsumer.ServiceReference1.GetDataResponse retVal = ((WCFDataServiceConsumer.ServiceReference1.IService1)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetDataResponse> WCFDataServiceConsumer.ServiceReference1.IService1.GetDataAsync(WCFDataServiceConsumer.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetDataResponse> GetDataAsync(int value) {
            WCFDataServiceConsumer.ServiceReference1.GetDataRequest inValue = new WCFDataServiceConsumer.ServiceReference1.GetDataRequest();
            inValue.Body = new WCFDataServiceConsumer.ServiceReference1.GetDataRequestBody();
            inValue.Body.value = value;
            return ((WCFDataServiceConsumer.ServiceReference1.IService1)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponse WCFDataServiceConsumer.ServiceReference1.IService1.GetDataUsingDataContract(WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public WCFDataServiceConsumer.ServiceReference1.CompositeType GetDataUsingDataContract(WCFDataServiceConsumer.ServiceReference1.CompositeType composite) {
            WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest inValue = new WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest();
            inValue.Body = new WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequestBody();
            inValue.Body.composite = composite;
            WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponse retVal = ((WCFDataServiceConsumer.ServiceReference1.IService1)(this)).GetDataUsingDataContract(inValue);
            return retVal.Body.GetDataUsingDataContractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponse> WCFDataServiceConsumer.ServiceReference1.IService1.GetDataUsingDataContractAsync(WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(WCFDataServiceConsumer.ServiceReference1.CompositeType composite) {
            WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest inValue = new WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequest();
            inValue.Body = new WCFDataServiceConsumer.ServiceReference1.GetDataUsingDataContractRequestBody();
            inValue.Body.composite = composite;
            return ((WCFDataServiceConsumer.ServiceReference1.IService1)(this)).GetDataUsingDataContractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFDataServiceConsumer.ServiceReference1.GetPersonResponse WCFDataServiceConsumer.ServiceReference1.IService1.GetPerson(WCFDataServiceConsumer.ServiceReference1.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public WCFDataServiceConsumer.ServiceReference1.Person GetPerson(WCFDataServiceConsumer.ServiceReference1.Person person) {
            WCFDataServiceConsumer.ServiceReference1.GetPersonRequest inValue = new WCFDataServiceConsumer.ServiceReference1.GetPersonRequest();
            inValue.Body = new WCFDataServiceConsumer.ServiceReference1.GetPersonRequestBody();
            inValue.Body.person = person;
            WCFDataServiceConsumer.ServiceReference1.GetPersonResponse retVal = ((WCFDataServiceConsumer.ServiceReference1.IService1)(this)).GetPerson(inValue);
            return retVal.Body.GetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetPersonResponse> WCFDataServiceConsumer.ServiceReference1.IService1.GetPersonAsync(WCFDataServiceConsumer.ServiceReference1.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFDataServiceConsumer.ServiceReference1.GetPersonResponse> GetPersonAsync(WCFDataServiceConsumer.ServiceReference1.Person person) {
            WCFDataServiceConsumer.ServiceReference1.GetPersonRequest inValue = new WCFDataServiceConsumer.ServiceReference1.GetPersonRequest();
            inValue.Body = new WCFDataServiceConsumer.ServiceReference1.GetPersonRequestBody();
            inValue.Body.person = person;
            return ((WCFDataServiceConsumer.ServiceReference1.IService1)(this)).GetPersonAsync(inValue);
        }
    }
}
